### PR TITLE
non-zero type arbitrary impls

### PR DESCRIPTION
**Pull request by jkosh44**

### CODE REVIEW

**Comment by jkosh44** [comment]
I tried pulling in all of `master`, but there were a lot of merge conflicts and I ended up basically resolving them at random: https://github.com/MaterializeInc/proptest/pull/2.

This is the only commit I actually care about.

**Review by ParkMyCar — APPROVED** [review]
Makes sense to me!

**Comment by jkosh44** [comment]
The GH Actions have been queued for almost 24 hours.

**Comment by jkosh44** [comment]
I have a test branch in the Materialize repo that uses this branch. Once that passes CI, I'll merge this.

https://github.com/MaterializeInc/materialize/pull/23370/files

**Pull request merged**
